# -*- coding: utf-8 -*-
"""
Created on Sun Mar 30 15:34:26 2025

@author: Leonimer

https://www.geeksforgeeks.org/generative-adversarial-network-gan/

How does a GAN work?
Let’s understand how the generator (G) and discriminator (D) complete to improve 
each other over time:

1. Generator’s First Move
G takes a random noise vector as input. This noise vector contains random values and 
acts as the starting point for G’s creation process. Using its internal layers and 
learned patterns, G transforms the noise vector into a new data sample, like a 
generated image.

2. Discriminator’s Turn
D receives two kinds of inputs:
Real data samples from the training dataset.
The data samples generated by G in the previous step.
D’s job is to analyze each input and determine whether it’s real data or something 
G cooked up. It outputs a probability score between 0 and 1. A score of 1 indicates 
the data is likely real, and 0 suggests it’s fake.

3. Adversarial Learning
If the discriminator correctly classifies real data as real and fake data as fake, 
it strengthens its ability slightly.
If the generator successfully fools the discriminator, it receives a positive update, 
while the discriminator is penalized.

4. Generator’s Improvement
Every time the discriminator misclassifies fake data as real, the generator learns and 
improves. Over multiple iterations, the generator produces more convincing synthetic 
samples.

5. Discriminator’s Adaptation
The discriminator continuously refines its ability to distinguish real from fake data. 
This ongoing duel between the generator and discriminator enhances the overall model’s 
learning process.

6. Training Progression
As training continues, the generator becomes highly proficient at producing realistic data.
Eventually, the discriminator struggles to distinguish real from fake, indicating that the 
GAN has reached a well-trained state.
At this point, the generator can be used to generate high-quality synthetic data for 
various applications.
"""

'''
Implementation of Generative Adversarial Network (GAN) using PyTorch
====================================================================
Let’s explore the implementation of a Generative Adversarial Network (GAN). 
Our GAN will be trained on the CIFAR-10 dataset to generate realistic images.

Step 1: Importing Required Libraries
First, we import the necessary libraries for building and training our GAN.
'''

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np

# set for training, reset for inference
isTraining = True
isTraining = False

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('device:', device)

'''
Step 2: Defining Image Transformations
We use PyTorch’s transforms to normalize and convert images into tensors 
before feeding them into the model.
'''
# Define a basic transform
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

'''
Step 3: Loading the CIFAR-10 Dataset
The CIFAR-10 dataset is loaded with predefined transformations. A DataLoader is 
created to process the dataset in mini-batches of 32 images, shuffled for randomness.
'''
path_data = 'C:\\Leo\\python scripts\\data'
train_dataset = datasets.CIFAR10(root=path_data, train=True, download=True, transform=transform)
dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True)

# plot samples of original dataset
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
figure = plt.figure(figsize=(6, 6))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(train_dataset), size=(1,)).item()
    img, label = train_dataset[sample_idx]
    img = img / 2 + 0.5     # unnormalize
    figure.add_subplot(rows, cols, i)
    plt.axis("off")
    plt.title(classes[label])
    plt.imshow(img.permute(1,2,0).squeeze())
plt.show()

'''
Step 4: Building the Generator
The generator, an 'inverted' convolutional neural network (CNN), takes a random latent vector (z) 
as input and transforms it into an image through convolutional, batch normalization, 
and upsampling layers. The final output uses Tanh activation to ensure pixel values 
are within the expected range.
'''
# Define the generator
class Generator(nn.Module):
    def __init__(self, latent_dim):
        super(Generator, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(latent_dim, 128 * 8 * 8),
            nn.ReLU(),
            nn.Unflatten(1, (128, 8, 8)),
            nn.Upsample(scale_factor=2),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128, momentum=0.78),
            nn.ReLU(),
            nn.Upsample(scale_factor=2),
            nn.Conv2d(128, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64, momentum=0.78),
            nn.ReLU(),
            nn.Conv2d(64, 3, kernel_size=3, padding=1),
            nn.Tanh()
        )

    def forward(self, z):
        img = self.model(z)
        return img

'''
Step 5: Building the Discriminator
The discriminator is a binary classifier that distinguishes between real and generated 
images. It consists of convolutional layers, batch normalization, dropout, and LeakyReLU 
activation to improve learning stability.
'''
# Define the discriminator
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()

        self.model = nn.Sequential(
        nn.Conv2d(3, 32, kernel_size=3, stride=2, padding=1),
        nn.LeakyReLU(0.2),
        nn.Dropout(0.25),
        nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1),
        nn.ZeroPad2d((0, 1, 0, 1)),
        nn.BatchNorm2d(64, momentum=0.82),
        nn.LeakyReLU(0.25),
        nn.Dropout(0.25),
        nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
        nn.BatchNorm2d(128, momentum=0.82),
        nn.LeakyReLU(0.2),
        nn.Dropout(0.25),
        nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
        nn.BatchNorm2d(256, momentum=0.8),
        nn.LeakyReLU(0.25),
        nn.Dropout(0.25),
        nn.Flatten(),
        nn.Linear(256 * 5 * 5, 1),
        nn.Sigmoid()
    )

    def forward(self, img):
        validity = self.model(img)
        return validity

'''
Step 6: Defining GAN Hyperparameters. Key hyperparameters are defined:
latent_dim – Dimensionality of the noise vector.
lr – Learning rate of the optimizer.
beta1, beta2 – Adam optimizer coefficients.
num_epochs – Total training iterations.
'''
# Hyperparameters
latent_dim = 100
lr = 0.0002
beta1 = 0.5
beta2 = 0.999
# num_epochs = 1000

'''
Step 7: Initializing GAN Components
Generator and Discriminator are initialized on the available device (GPU or CPU).
Binary Cross-Entropy (BCE) Loss is chosen as the loss function.
Adam optimizers are defined separately for the generator and discriminator with 
specified learning rates and betas.
'''
# Define the generator and discriminator
# Initialize generator and discriminator
generator = Generator(latent_dim).to(device)
discriminator = Discriminator().to(device)
# Loss function
adversarial_loss = nn.BCELoss()
# Optimizers
optimizer_G = optim.Adam(generator.parameters()\
                         , lr=lr, betas=(beta1, beta2))
optimizer_D = optim.Adam(discriminator.parameters()\
                         , lr=lr, betas=(beta1, beta2))

# plot generated images
def plot_images(nr=16, epoch=1):
    with torch.no_grad():
        z = torch.randn(nr, latent_dim, device=device)
        generated = generator(z).detach().cpu()
        grid = torchvision.utils.make_grid(generated, nrow=int(np.sqrt(nr)), normalize=True)
        plt.imshow(np.transpose(grid, (1, 2, 0)))
        plt.axis("off")
        plt.title("Epoch: " + str(epoch))
        plt.show()
        
'''
Step 8: Training the GAN
The discriminator is trained to differentiate between real and fake images.
The generator is trained to produce realistic images that fool the discriminator.
The loss is backpropagated using Adam optimizers, and the model updates its parameters.
Progress tracking: Loss values for both networks are printed, and generated images are 
displayed every 10 epochs for visual inspection.
'''
# Training loop
num_epochs = 5

if isTraining:
    # plot no training generated images
    plot_images(25, 0) 
    for epoch in range(num_epochs):
        for i, batch in enumerate(dataloader):
           # Convert list to tensor
            real_images = batch[0].to(device) 
            # Adversarial ground truths
            valid = torch.ones(real_images.size(0), 1, device=device)
            fake = torch.zeros(real_images.size(0), 1, device=device)
            # Configure input
            real_images = real_images.to(device)
    
            # ---------------------
            #  Train Discriminator
            # ---------------------
            optimizer_D.zero_grad()
            # Sample noise as generator input
            z = torch.randn(real_images.size(0), latent_dim, device=device)
            # Generate a batch of images
            fake_images = generator(z)
    
            # Measure discriminator's ability 
            # to classify real and fake images
            real_loss = adversarial_loss(discriminator\
                                         (real_images), valid)
            fake_loss = adversarial_loss(discriminator\
                                         (fake_images.detach()), fake)
            d_loss = (real_loss + fake_loss) / 2
            # Backward pass and optimize
            d_loss.backward()
            optimizer_D.step()
    
            # -----------------
            #  Train Generator
            # -----------------
            optimizer_G.zero_grad()
            # Generate a batch of images
            gen_images = generator(z)
            # Adversarial loss
            g_loss = adversarial_loss(discriminator(gen_images), valid)
            # Backward pass and optimize
            g_loss.backward()
            optimizer_G.step()
            
            # ---------------------
            #  Progress Monitoring
            # ---------------------
            if (i + 1) % 100 == 0:
                print(
                    f"Epoch [{epoch+1}/{num_epochs}] Batch {i+1}/{len(dataloader)} "
                    f"Discr. Loss: {d_loss.item():.4f} "
                    f"Gener. Loss: {g_loss.item():.4f}"
                )
                
        # plot generated images for every epoch
        plot_images(25, epoch+1) 
        
        # if (epoch + 1) % 10 == 0:
            # plot_images()   
        # with torch.no_grad():
        #     z = torch.randn(16, latent_dim, device=device)
        #     generated = generator(z).detach().cpu()
        #     grid = torchvision.utils.make_grid(generated, nrow=4, normalize=True)
        #     plt.imshow(np.transpose(grid, (1, 2, 0)))
        #     plt.axis("off")
        #     plt.show()

'''
We have successfully implemented a GAN in PyTorch and trained it on CIFAR-10. 
The generator learns to create realistic images, while the discriminator helps in 
refining them through adversarial training.
'''

path = 'C:\\Leo\\python scripts\\GANs\\'

if isTraining:
    '''
    Saving Model for inference
    ==========================
    A common way to save a model is to serialize the internal state dictionary 
    (containing the model parameters).
    '''
    torch.save(generator.state_dict(), path + "generator.pth")
    print("Saved PyTorch Model State to generator.pth")

if not isTraining:
    # Loading Model for inference
    generator = Generator(latent_dim).to(device)
    generator.load_state_dict(torch.load(path + "generator.pth", weights_only=True))
    print("Loaded PyTorch Model State from generator.pth")

# plot generated images with pretreined GAN
plot_images(25, 'x')
